# Generated by Django 2.1.2 on 2018-10-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oanda_id", models.CharField(max_length=64)),
                ("balance", models.DecimalField(decimal_places=5, max_digits=16)),
            ],
        )
    ]
